=== tjwoodall/business-details-api/resources/public/api/conf/1.0/schemas/retrieveBusinessDetails/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve additional information for a user's business details",
  "description": "Retrieve business details response",
  "type": "object",
  "properties": {
    "businessId": {
      "type": "string",
      "description": "A unique identifier for the business income source. Previously known as selfEmploymentId.",
      "example": "XAIS12345678910",
      "pattern": "^X[a-zA-Z0-9]{1}IS[0-9]{11}$"
    },
    "typeOfBusiness": {
      "type": "string",
      "description": "The type of business income source.",
      "enum": [
        "self-employment",
        "uk-property",
        "foreign-property",
        "property-unspecified"
      ]
    },
    "tradingName": {
      "type": "string",
      "description": "The trading name of the business.",
      "example": "ABC Ltd."
    },
  "yearOfMigration": {
      "type": "string",
      "description": "Year of migration.",
      "pattern": "^(\\d{4})$",
      "example": "2022"
    },
    "firstAccountingPeriodStartDate": {
      "type": "string",
      "description": "The first accounting period start date.\n\nNote: <b>Accounting period start and end dates should not be displayed to users of your software.</b>",
      "format": "date",
      "example": "2019-09-30",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "firstAccountingPeriodEndDate": {
      "type": "string",
      "description": "The first accounting period end date.\n\nNote: <b>Accounting period start and end dates should not be displayed to users of your software.</b>",
      "format": "date",
      "example": "2020-02-29",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "latencyDetails": {
      "type": "object",
      "description": "Income source latency details.",
      "properties": {
        "latencyEndDate": {
          "type": "string",
          "description": "End date of latency period for the income source.",
          "example": "2020-02-27",
          "format": "date",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
        },
        "taxYear1": {
          "type": "string",
          "description": "First tax year for the income source.",
          "example": "2018-19",
          "format": "tax-year",
          "minimum": 7,
          "maximum": 7
        },
        "latencyIndicator1": {
          "type": "string",
          "description": "Self assessment submission frequency.",
          "enum": [
            "A",
            "Q"
          ],
          "minimum": 1,
          "maximum": 1,
          "example": "A"
        },
        "taxYear2": {
          "type": "string",
          "description": "Second tax year for the income source.",
          "example": "2019-20",
          "format": "tax-year",
          "minimum": 7,
          "maximum": 7
        },
        "latencyIndicator2": {
          "type": "string",
          "description": "Self assessment submission frequency.",
          "enum": [
            "A",
            "Q"
          ],
          "minimum": 1,
          "maximum": 1,
          "example": "A"
        }
      },
      "required": [
        "latencyEndDate",
        "taxYear1",
        "latencyIndicator1",
        "taxYear2",
        "latencyIndicator2"
      ]
    },
    "quarterlyTypeChoice": {
      "type": "object",
      "description": "Quarterly reporting period type.",
      "properties": {
        "quarterlyPeriodType": {
          "type": "string",
          "enum": ["standard", "calendar"],
          "description": "The quarterly period type that is being chosen for the business ID.",
          "example": "standard"
        },
        "taxYearOfChoice": {
          "type": "string",
          "description": "The tax year for which the quarterly period type was chosen.",
          "pattern": "^2[0-9]{3}-[0-9]{2}$",
          "example": "2023-24"
        }
      },
      "required": [
        "quarterlyPeriodType",
        "taxYearOfChoice"
      ]
    },
    "accountingPeriods": {
      "type": "array",
      "description": "The start and end dates of the latest accounting period for the business. This array contains dates for the latest accounting period only.\n\nNote: <b>Accounting period start and end dates should not be displayed to users of your software.</b>",
      "items": {
        "type": "object",
        "properties": {
          "start": {
            "description": "Date your books or accounts start - the beginning of your accounting period.",
            "type": "string",
            "example": "2018-04-06"
          },
          "end": {
            "description": "Date your books or accounts are made up to - the end of your accounting period.",
            "type": "string",
            "example": "2019-04-05"
          }
        },
        "required": [
          "start",
          "end"
        ],
        "additionalProperties": false
      }
    },
    "commencementDate": {
      "description": "Business start date, must be in the past.",
      "type": "string",
      "example": "2016-09-24"
    },
    "cessationDate": {
      "description": "Business cessation date.",
      "type": "string",
      "example": "2020-03-24"
    },
    "businessAddressLineOne": {
      "description": "First line of the business address.",
      "type": "string",
      "example": "1 ABC Rd."
    },
    "businessAddressLineTwo": {
      "description": "Second line of the business address.",
      "type": "string",
      "example": "London"
    },
    "businessAddressLineThree": {
      "description": "Third line of the business address.",
      "type": "string",
      "example": "Greater London"
    },
    "businessAddressLineFour": {
      "description": "Fourth line of the business address.",
      "type": "string",
      "example": "United Kingdom"
    },
    "businessAddressPostcode": {
      "description": "Business code.",
      "type": "string",
      "example": "M1 1AG"
    },
    "businessAddressCountryCode": {
      "description": "ISO country code for the business if it is in a non-GB country. The two-letter code for a country must adhere to ISO 3166.",
      "type": "string",
      "example": "FR"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource.",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint.",
            "type": "string",
            "example": "/individuals/business/details/CX897463D/XAIS12345678910"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource\nThe rel will be self where the action is retrieval of the same resource.",
            "type": "string",
            "enum": [
              "self"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint.",
            "type": "string",
            "enum": [
              "GET"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "businessId",
    "typeOfBusiness",
    "accountingPeriods"
  ],
  "additionalProperties": false
}

=== tjwoodall/business-details-api/resources/public/api/conf/1.0/examples/retrieveBusinessDetails/response.json
{
  "businessId": "XAIS12345678910",
  "typeOfBusiness": "self-employment",
  "tradingName": "ABC Ltd.",
  "yearOfMigration": "2022",
  "firstAccountingPeriodStartDate": "2019-09-30",
  "firstAccountingPeriodEndDate": "2020-02-29",
  "latencyDetails": {
    "latencyEndDate": "2020-02-27",
    "taxYear1": "2018-19",
    "latencyIndicator1": "A",
    "taxYear2": "2019-20",
    "latencyIndicator2": "A"
  },
  "accountingPeriods": [
    {
      "start": "2023-04-06",
      "end": "2024-04-05"
    }
  ],
  "quarterlyTypeChoice": {
    "quarterlyPeriodType": "standard",
    "taxYearOfChoice": "2023-24"
  },
  "commencementDate": "2023-04-06",
  "cessationDate": "2024-04-05",
  "businessAddressLineOne": "1 Acme Rd.",
  "businessAddressLineTwo": "London",
  "businessAddressLineThree": "Greater London",
  "businessAddressLineFour": "United Kingdom",
  "businessAddressPostcode": "M1 1AG",
  "businessAddressCountryCode": "GB",
  "links": [
    {
      "href": "/individuals/business/details/ET009363D/XAIS12345678910",
      "method": "GET",
      "rel": "self"
    }
  ]
}
